workflows:
  ios-godot:
    name: iOS Godot 4.6.1 Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    scripts:
      - name: Install dependencies
        script: |
          brew update
          brew install curl unzip || true

      - name: Download Godot 4.6.1
        script: |
          set -e
          mkdir -p tools
          cd tools

          echo "Downloading Godot..."
          curl -L --fail -o godot.zip \
          https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_macos.universal.zip

          unzip -o godot.zip
          chmod +x Godot*.app/Contents/MacOS/Godot*

      - name: Download export templates
        script: |
          set -e
          cd tools

          echo "Downloading templates..."
          curl -L --fail -o templates.tpz \
          https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_export_templates.tpz

          mkdir -p "$HOME/Library/Application Support/Godot/export_templates/4.6.1.stable"

          unzip -o templates.tpz

          # Перемещаем ios.zip туда, куда Godot ожидает
          mv templates/* "$HOME/Library/Application Support/Godot/export_templates/4.6.1.stable/"


      - name: Export iOS project
        script: |
          set -e

          echo "Exporting iOS..."
          mkdir -p build

          GODOT_BIN=$(find tools -type f -path "*Godot*.app/Contents/MacOS/*" | head -n 1)

          "$GODOT_BIN" --headless --path . --export-release "iOS" "build"

          echo "Listing build directory:"
          find build -maxdepth 4 -type d -print
          find build -maxdepth 4 -name "*.xcodeproj" -print

      - name: Debug export folder
        script: |
          echo "Listing build directory"
          ls -R build

      - name: Build IPA
        script: |
          set -e
          cd build/ios

          XCODEPROJ=$(find . -name "*.xcodeproj" | head -n 1)
          echo "Project: $XCODEPROJ"

          SCHEME=$(xcodebuild -list -project "$XCODEPROJ" | awk '/Schemes:/{flag=1;next} flag && NF{print; exit}')
          echo "Scheme: $SCHEME"

          xcodebuild \
            -project "$XCODEPROJ" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            archive

          cat > "$CM_BUILD_DIR/ExportOptions.plist" <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>automatic</string>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportPath "$CM_BUILD_DIR/ipa" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist"

    artifacts:
      - ipa/*.ipa
