workflows:
  ios-godot:
    name: iOS Godot 4.6.1 Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    scripts:
      - name: Install dependencies
        script: |
          brew update
          brew install curl unzip || true

      - name: Download Godot 4.6.1
        script: |
          set -e
          mkdir -p tools
          cd tools

          echo "Downloading Godot..."
          curl -L --fail -o godot.zip \
            https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_macos.universal.zip

          unzip -o godot.zip
          chmod +x Godot*.app/Contents/MacOS/Godot* || true

      - name: Download export templates
        script: |
          set -e
          mkdir -p tools
          cd tools

          echo "Downloading templates..."
          curl -L --fail -o templates.tpz \
            https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_export_templates.tpz

          # Godot ожидает zip-шаблоны прямо в папке версии (например ios.zip)
          TEMPL_DIR="$HOME/Library/Application Support/Godot/export_templates/4.6.1.stable"
          mkdir -p "$TEMPL_DIR"

          rm -rf templates || true
          unzip -o templates.tpz

          # Внутри tpz обычно есть папка templates/ с ios.zip и т.п.
          if [ -d "templates" ]; then
            mv -f templates/* "$TEMPL_DIR/"
          else
            # на всякий случай, если структура другая
            mv -f ./*.zip "$TEMPL_DIR/" || true
          fi

          echo "Templates installed. Contents:"
          ls -la "$TEMPL_DIR" || true

      - name: Export iOS project
        script: |
          set -e
          echo "Exporting iOS..."
          mkdir -p "./build/ios"

          GODOT_BIN=$(find tools -type f -path "*Godot*.app/Contents/MacOS/*" | head -n 1)
          echo "Using Godot: $GODOT_BIN"

          "$GODOT_BIN" --headless --path . --export-release "iOS" "./build/ios"

          echo "Export directory tree:"
          find ./build -maxdepth 4 -type d -print || true
          echo "Xcode projects found:"
          find ./build -maxdepth 6 -name "*.xcodeproj" -print || true

      - name: Build IPA
        script: |
          set -e

          # Ищем .xcodeproj где бы он ни оказался внутри ./build
          XCODEPROJ=$(find ./build -maxdepth 8 -name "*.xcodeproj" | head -n 1)
          echo "Project: $XCODEPROJ"

          if [ -z "$XCODEPROJ" ]; then
            echo "No .xcodeproj found after export!"
            echo "Files under ./build:"
            find ./build -maxdepth 8 -type f -print || true
            exit 1
          fi

          # Узнаём первую доступную схему
          xcodebuild -list -project "$XCODEPROJ"
          SCHEME=$(xcodebuild -list -project "$XCODEPROJ" | awk '/Schemes:/{flag=1;next} flag && NF{print; exit}')
          echo "Scheme: $SCHEME"

          if [ -z "$SCHEME" ]; then
            echo "No scheme found in project!"
            exit 1
          fi

          # Архивируем
          xcodebuild \
            -project "$XCODEPROJ" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            archive

          # Экспорт IPA (под App Store). На этом шаге позже может потребоваться signing.
          cat > "$CM_BUILD_DIR/ExportOptions.plist" <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>automatic</string>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportPath "$CM_BUILD_DIR/ipa" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist"

    artifacts:
      - ipa/*.ipa
      - build/**/*
