workflows:
  ios-godot:
    name: iOS Godot 4.6.1 Build (App Store)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      vars:
        GODOT_TEMPL_VERSION_DIR: "4.6.1.stable"
        EXPORT_PRESET: "iOS"
      ios_signing:
        provisioning_profiles:
          - ICEFISH_APPSTORE_PROFILE
        # если в Codemagic сертификат тоже с reference name — добавь сюда:
        # certificates:
        #   - ICEFISH_DIST_CERT

    scripts:
      - name: Install dependencies
        script: |
          brew update
          brew install curl unzip || true

      - name: Download Godot 4.6.1
        script: |
          set -e
          mkdir -p tools
          cd tools
          curl -L --fail -o godot.zip \
            https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_macos.universal.zip
          unzip -o godot.zip
          chmod +x Godot*.app/Contents/MacOS/Godot* || true

      - name: Download export templates
        script: |
          set -e
          mkdir -p tools
          cd tools
          curl -L --fail -o templates.tpz \
            https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_export_templates.tpz

          TEMPL_DIR="$HOME/Library/Application Support/Godot/export_templates/${GODOT_TEMPL_VERSION_DIR}"
          mkdir -p "$TEMPL_DIR"

          rm -rf templates || true
          unzip -o templates.tpz
          if [ -d "templates" ]; then
            mv -f templates/* "$TEMPL_DIR/"
          else
            mv -f ./*.zip "$TEMPL_DIR/" || true
          fi

          echo "Templates installed:"
          ls -la "$TEMPL_DIR" || true

      - name: Export iOS project
        script: |
          set -e
          mkdir -p "./build/ios"
          GODOT_BIN=$(find tools -type f -path "*Godot*.app/Contents/MacOS/*" | head -n 1)
          echo "Using Godot: $GODOT_BIN"
          "$GODOT_BIN" --headless --path . --export-release "${EXPORT_PRESET}" "./build/ios"

          echo "Xcode projects found:"
          find ./build -maxdepth 8 -name "*.xcodeproj" -print || true

      - name: Build IPA (Codemagic signing)
        script: |
          set -e

          XCODEPROJ=$(find ./build -maxdepth 10 -name "*.xcodeproj" | head -n 1)
          echo "Project: $XCODEPROJ"
          [ -n "$XCODEPROJ" ]

          SCHEME=$(xcodebuild -list -project "$XCODEPROJ" \
            | awk '/Schemes:/{flag=1;next} flag && NF{print; exit}' \
            | xargs)
          echo "Scheme: $SCHEME"
          [ -n "$SCHEME" ]

          # применяем профили из ios_signing (убирает конфликт signing)
          xcode-project use-profiles --project "$XCODEPROJ"

          xcodebuild \
            -project "$XCODEPROJ" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            archive
          
          cat > "$CM_BUILD_DIR/ExportOptions.plist" <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.cerentaner.icefishadventure</key>
              <string>IceFishProfile</string>
            </dict>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportPath "ipa" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist"

    publishing:
      app_store_connect:
        api_key: ASC_KEY
        key_id: $APPSTORE_KEY_ID
        issuer_id: $APPSTORE_ISSUER_ID
        submit_to_testflight: true

    artifacts:
      - ipa/*.ipa
      - build/**/*
